project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "about.qmd"
    - "research.qmd"
    - "projects.qmd"
    - "teaching.qmd"
    - "blog/index.qmd"
    - "blog/**/*.qmd"
    - "404.qmd"
  resources:
    - "content/"
    - "css/"
    - "images/"
    - "project-items/"
    - "synoptreg/"

execute:
  freeze: auto

website:
  title: "Marc Lemus-Canovas"
  description: "Postdoctoral Researcher in Climate Change | Pyrenees | R programming"
  image: images/profile.jpg
  site-url: https://lemuscanovas.github.io
  favicon: images/favicon.ico
  repo-url: https://github.com/lemuscanovas/lemuscanovas.github.io
  search:
    location: navbar
    type: overlay
  back-to-top-navigation: false
  open-graph:
    locale: en_US
    site-name: lemuscanovas.github.io

  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Blog"
        href: blog/index.qmd

  page-footer:
    center:
      - text: "<a href='https://github.com/lemuscanovas' target='blank'><i class='bi bi-github'></i></a>
        &nbsp;<a href='https://bsky.app/profile/lemuscanovas.bsky.social' target='blank'><i class='fa fa-brands fa-bluesky'></i></a>
        &nbsp;<a href='https://www.linkedin.com/in/marc-lemus-canovas' target='blank'><i class='bi bi-linkedin'></i></a>
        &nbsp;<a href='https://scholar.google.com/citations?user=iOCaO7sAAAAJ' target='blank'><i class='ai ai-google-scholar fa-lg'></i></a>
        &nbsp;<a href='https://orcid.org/0000-0002-0925-3827' target='blank'><i class='ai ai-orcid fa-lg'></i></a>
        &nbsp;<a href='https://www.researchgate.net/profile/Marc-Lemus-Canovas' target='blank'><i class='ai ai-researchgate fa-lg'></i></a>
        <br>Site made with <i class='bi bi-heart-fill'></i> and
        <img src='https://quarto.org/favicon.png' width=12> quarto
        <br>&copy; 2026 Marc Lemus-Canovas"

format:
  html:
    theme: [default, css/theme.scss]
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    lightbox: true
    include-in-header: "_includes/header.html"
